package com.example.driveronboarding.enums;

public enum DriverStatus {
    ACTIVE,
    INACTIVE,
    CREATED,
    DOC_VERIFICATION_COMPLETED,
    DOC_VERIFICATION_FAILED,
    BACKGROUND_VERIFICATION_COMPLETED,
    BACKGROUND_VERIFICATION_FAILED,
    ASSET_COLLECTION_COMPLETED,
    ASSET_COLLECTION_FAILED,
    TRAINING_COMPLETED,
    TRAINING_FAILED
}
